# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movedialogui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(274, 184)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_relatively = QtWidgets.QRadioButton(Dialog)
        self.rb_relatively.setChecked(True)
        self.rb_relatively.setObjectName("rb_relatively")
        self.horizontalLayout_2.addWidget(self.rb_relatively)
        self.rb_absolutly = QtWidgets.QRadioButton(Dialog)
        self.rb_absolutly.setObjectName("rb_absolutly")
        self.horizontalLayout_2.addWidget(self.rb_absolutly)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.et_val_x = QtWidgets.QLineEdit(Dialog)
        self.et_val_x.setObjectName("et_val_x")
        self.horizontalLayout_6.addWidget(self.et_val_x)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.et_val_y = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.et_val_y.sizePolicy().hasHeightForWidth())
        self.et_val_y.setSizePolicy(sizePolicy)
        self.et_val_y.setObjectName("et_val_y")
        self.horizontalLayout_4.addWidget(self.et_val_y)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.et_val_z = QtWidgets.QLineEdit(Dialog)
        self.et_val_z.setObjectName("et_val_z")
        self.horizontalLayout_3.addWidget(self.et_val_z)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_move_insert = QtWidgets.QPushButton(Dialog)
        self.btn_move_insert.setObjectName("btn_move_insert")
        self.horizontalLayout.addWidget(self.btn_move_insert)
        self.btn_move_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_move_cancel.setObjectName("btn_move_cancel")
        self.horizontalLayout.addWidget(self.btn_move_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "插入行进语句"))
        self.rb_relatively.setText(_translate("Dialog", "相对移动"))
        self.rb_absolutly.setText(_translate("Dialog", "绝对移动"))
        self.label_3.setText(_translate("Dialog", "X值："))
        self.label.setText(_translate("Dialog", "Y值："))
        self.label_2.setText(_translate("Dialog", "Z值："))
        self.btn_move_insert.setText(_translate("Dialog", "插入"))
        self.btn_move_cancel.setText(_translate("Dialog", "取消"))


