# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mianwin.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/app_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.program_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.program_edit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.program_edit.setObjectName("program_edit")
        self.verticalLayout.addWidget(self.program_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.about = LabelClickable(self.centralwidget)
        self.about.setObjectName("about")
        self.horizontalLayout.addWidget(self.about)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.build = QtWidgets.QMenu(self.menubar)
        self.build.setObjectName("build")
        self.insert = QtWidgets.QMenu(self.menubar)
        self.insert.setEnabled(False)
        self.insert.setObjectName("insert")
        self.menu_2 = QtWidgets.QMenu(self.insert)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.program_menu = QtWidgets.QAction(MainWindow)
        self.program_menu.setObjectName("program_menu")
        self.lib_menu = QtWidgets.QAction(MainWindow)
        self.lib_menu.setObjectName("lib_menu")
        self.jiami_menu = QtWidgets.QAction(MainWindow)
        self.jiami_menu.setObjectName("jiami_menu")
        self.val_menu = QtWidgets.QAction(MainWindow)
        self.val_menu.setCheckable(False)
        self.val_menu.setEnabled(True)
        self.val_menu.setObjectName("val_menu")
        self.if_menu = QtWidgets.QAction(MainWindow)
        self.if_menu.setObjectName("if_menu")
        self.move_menu = QtWidgets.QAction(MainWindow)
        self.move_menu.setObjectName("move_menu")
        self.avoid_menu = QtWidgets.QAction(MainWindow)
        self.avoid_menu.setObjectName("avoid_menu")
        self.speed_menu = QtWidgets.QAction(MainWindow)
        self.speed_menu.setObjectName("speed_menu")
        self.xyz_menu = QtWidgets.QAction(MainWindow)
        self.xyz_menu.setObjectName("xyz_menu")
        self.din_menu = QtWidgets.QAction(MainWindow)
        self.din_menu.setObjectName("din_menu")
        self.dout_menu = QtWidgets.QAction(MainWindow)
        self.dout_menu.setObjectName("dout_menu")
        self.delay_menu = QtWidgets.QAction(MainWindow)
        self.delay_menu.setObjectName("delay_menu")
        self.call_menu = QtWidgets.QAction(MainWindow)
        self.call_menu.setObjectName("call_menu")
        self.dindout_menu = QtWidgets.QAction(MainWindow)
        self.dindout_menu.setObjectName("dindout_menu")
        self.move_menu_2 = QtWidgets.QAction(MainWindow)
        self.move_menu_2.setObjectName("move_menu_2")
        self.build.addAction(self.program_menu)
        self.build.addAction(self.lib_menu)
        self.build.addAction(self.jiami_menu)
        self.menu_2.addAction(self.speed_menu)
        self.menu_2.addAction(self.xyz_menu)
        self.insert.addAction(self.val_menu)
        self.insert.addAction(self.if_menu)
        self.insert.addSeparator()
        self.insert.addAction(self.menu_2.menuAction())
        self.insert.addAction(self.move_menu_2)
        self.insert.addAction(self.delay_menu)
        self.insert.addAction(self.call_menu)
        self.insert.addAction(self.dindout_menu)
        self.menubar.addAction(self.build.menuAction())
        self.menubar.addAction(self.insert.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "wiring"))
        self.about.setText(_translate("MainWindow", "当前版本号：V0.1"))
        self.build.setTitle(_translate("MainWindow", "新建"))
        self.insert.setTitle(_translate("MainWindow", "插入"))
        self.menu_2.setTitle(_translate("MainWindow", "系统指令"))
        self.program_menu.setText(_translate("MainWindow", "新建程序"))
        self.lib_menu.setText(_translate("MainWindow", "新建子程序"))
        self.jiami_menu.setText(_translate("MainWindow", "新建加密程序"))
        self.val_menu.setText(_translate("MainWindow", "添加变量"))
        self.if_menu.setText(_translate("MainWindow", "if语句"))
        self.move_menu.setText(_translate("MainWindow", "行进操做"))
        self.avoid_menu.setText(_translate("MainWindow", "避障操作"))
        self.speed_menu.setText(_translate("MainWindow", "速度调节"))
        self.xyz_menu.setText(_translate("MainWindow", "坐标系切换"))
        self.din_menu.setText(_translate("MainWindow", "接收"))
        self.dout_menu.setText(_translate("MainWindow", "发送"))
        self.delay_menu.setText(_translate("MainWindow", "延时指令"))
        self.call_menu.setText(_translate("MainWindow", "引用指令"))
        self.dindout_menu.setText(_translate("MainWindow", "信号指令"))
        self.move_menu_2.setText(_translate("MainWindow", "行进指令"))


from diy.label_clickable import LabelClickable
import res_rc
